global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          [
            'gateway:3000',
            'users:3000',
            'email:3000',
            'videos:3000',
            'reaction:3000',
            'comments:3000',
            'views:3000',
            'subscribe:3000',
            'video-transcoder:3000',
            'projection:3000',
            'query:3000',
            'playlist:3000',
            'history:3000',
            'authz:3000',
          ]
