name: Playlist CI

on:
  push:
    paths:
      - "apps/playlist/**"
      - "libs/**"
      - ".github/workflows/playlist-service.yml"
      - "package.json"
      - "yarn.lock"
      - "jest.config.json"
      - "eslint.config.js"
      - "nest-cli.json"
      - "tsconfig.json"
      - "tsconfig.build.json"
  pull_request:
    paths:
      - "apps/playlist/**"
      - "libs/**"
      - ".github/workflows/playlist-service.yml"
      - "package.json"
      - "yarn.lock"
      - "jest.config.json"
      - "eslint.config.js"
      - "nest-cli.json"
      - "tsconfig.json"
      - "tsconfig.build.json"

jobs:
  playlist-pipeline:
    uses: ./.github/workflows/template-ci.yml
    with:
      service-name: "playlist"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
